version: "3.8"

services:
  gateway:
    networks:
      - local-shared
    build:
      context: .
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - PORT=8000
      - DEBUG=true
      - USER_IDENTITY_HEADER=x-amzn-oidc-identity
      - OIDC_DATA_HEADER=x-amzn-oidc-data
      - IDP_PROVIDER_NAME=${IDP_PROVIDER_NAME}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - IAM_SVC_ADDR=${IAM_SVC_ADDR}
      - PROJECT_SVC_ADDR=${PROJECT_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - AWS_SVC_ADDR=${AWS_SVC_ADDR}
      - OSINT_SVC_ADDR=${OSINT_SVC_ADDR}
      - DIAGNOSIS_SVC_ADDR=${DIAGNOSIS_SVC_ADDR}
      - CODE_SVC_ADDR=${CODE_SVC_ADDR}
    ports:
      - "8000:8000"

networks:
  local-shared:
    external: true
    
