// Code generated by protoc-gen-service. DO NOT EDIT.
// source: aws/service.proto

package main

import (
	"net/http"

	"github.com/ca-risken/datasource-api/proto/aws"
)

func (g *gatewayService) listAWSAwsHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	req := &aws.ListAWSRequest{}
	if err := bind(req, r); err != nil {
		appLogger.Warnf(ctx, "Failed to bind request, req=%s, err=%+v", "ListAWSRequest", err)
	}
	if err := req.Validate(); err != nil {
		writeResponse(ctx, w, http.StatusBadRequest, map[string]interface{}{errorJSONKey: err.Error()})
		return
	}
	resp, err := g.awsClient.ListAWS(ctx, req)
	if err != nil {
		writeResponse(ctx, w, http.StatusInternalServerError, grpcErrorMessage(ctx, err))
		return
	}
	writeResponse(ctx, w, http.StatusOK, map[string]interface{}{successJSONKey: resp})
}

func (g *gatewayService) putAWSAwsHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	req := &aws.PutAWSRequest{}
	if err := bind(req, r); err != nil {
		appLogger.Warnf(ctx, "Failed to bind request, req=%s, err=%+v", "PutAWSRequest", err)
	}
	if err := req.Validate(); err != nil {
		writeResponse(ctx, w, http.StatusBadRequest, map[string]interface{}{errorJSONKey: err.Error()})
		return
	}
	resp, err := g.awsClient.PutAWS(ctx, req)
	if err != nil {
		writeResponse(ctx, w, http.StatusInternalServerError, grpcErrorMessage(ctx, err))
		return
	}
	writeResponse(ctx, w, http.StatusOK, map[string]interface{}{successJSONKey: resp})
}

func (g *gatewayService) deleteAWSAwsHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	req := &aws.DeleteAWSRequest{}
	if err := bind(req, r); err != nil {
		appLogger.Warnf(ctx, "Failed to bind request, req=%s, err=%+v", "DeleteAWSRequest", err)
	}
	if err := req.Validate(); err != nil {
		writeResponse(ctx, w, http.StatusBadRequest, map[string]interface{}{errorJSONKey: err.Error()})
		return
	}
	resp, err := g.awsClient.DeleteAWS(ctx, req)
	if err != nil {
		writeResponse(ctx, w, http.StatusInternalServerError, grpcErrorMessage(ctx, err))
		return
	}
	writeResponse(ctx, w, http.StatusOK, map[string]interface{}{successJSONKey: resp})
}

func (g *gatewayService) listDataSourceAwsHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	req := &aws.ListDataSourceRequest{}
	if err := bind(req, r); err != nil {
		appLogger.Warnf(ctx, "Failed to bind request, req=%s, err=%+v", "ListDataSourceRequest", err)
	}
	if err := req.Validate(); err != nil {
		writeResponse(ctx, w, http.StatusBadRequest, map[string]interface{}{errorJSONKey: err.Error()})
		return
	}
	resp, err := g.awsClient.ListDataSource(ctx, req)
	if err != nil {
		writeResponse(ctx, w, http.StatusInternalServerError, grpcErrorMessage(ctx, err))
		return
	}
	writeResponse(ctx, w, http.StatusOK, map[string]interface{}{successJSONKey: resp})
}

func (g *gatewayService) detachDataSourceAwsHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	req := &aws.DetachDataSourceRequest{}
	if err := bind(req, r); err != nil {
		appLogger.Warnf(ctx, "Failed to bind request, req=%s, err=%+v", "DetachDataSourceRequest", err)
	}
	if err := req.Validate(); err != nil {
		writeResponse(ctx, w, http.StatusBadRequest, map[string]interface{}{errorJSONKey: err.Error()})
		return
	}
	resp, err := g.awsClient.DetachDataSource(ctx, req)
	if err != nil {
		writeResponse(ctx, w, http.StatusInternalServerError, grpcErrorMessage(ctx, err))
		return
	}
	writeResponse(ctx, w, http.StatusOK, map[string]interface{}{successJSONKey: resp})
}

func (g *gatewayService) invokeScanAwsHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	req := &aws.InvokeScanRequest{}
	if err := bind(req, r); err != nil {
		appLogger.Warnf(ctx, "Failed to bind request, req=%s, err=%+v", "InvokeScanRequest", err)
	}
	if err := req.Validate(); err != nil {
		writeResponse(ctx, w, http.StatusBadRequest, map[string]interface{}{errorJSONKey: err.Error()})
		return
	}
	resp, err := g.awsClient.InvokeScan(ctx, req)
	if err != nil {
		writeResponse(ctx, w, http.StatusInternalServerError, grpcErrorMessage(ctx, err))
		return
	}
	writeResponse(ctx, w, http.StatusOK, map[string]interface{}{successJSONKey: resp})
}
