// Code generated by protoc-gen-service. DO NOT EDIT.
// source: organization_iam/service.proto
// This file is intentionally empty. The organization_iam proto has been
// replaced by org_iam. See service_org_iam_generated.go for the new handlers.

package main
