// Code generated by protoc-gen-service. DO NOT EDIT.
// source: report/service.proto

package main

import (
	"net/http"

	"github.com/ca-risken/core/proto/report"
)

func (g *gatewayService) getReportFindingReportHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	req := &report.GetReportFindingRequest{}
	if err := bind(req, r); err != nil {
		appLogger.Warnf(ctx, "Failed to bind request, req=%s, err=%+v", "GetReportFindingRequest", err)
	}
	if err := req.Validate(); err != nil {
		writeResponse(ctx, w, http.StatusBadRequest, map[string]interface{}{errorJSONKey: err.Error()})
		return
	}
	resp, err := g.reportClient.GetReportFinding(ctx, req)
	if err != nil {
		writeResponse(ctx, w, http.StatusInternalServerError, grpcErrorMessage(ctx, err))
		return
	}
	writeResponse(ctx, w, http.StatusOK, map[string]interface{}{successJSONKey: resp})
}

func (g *gatewayService) getReportFindingAllReportHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	req := &report.GetReportFindingAllRequest{}
	if err := bind(req, r); err != nil {
		appLogger.Warnf(ctx, "Failed to bind request, req=%s, err=%+v", "GetReportFindingAllRequest", err)
	}
	if err := req.Validate(); err != nil {
		writeResponse(ctx, w, http.StatusBadRequest, map[string]interface{}{errorJSONKey: err.Error()})
		return
	}
	resp, err := g.reportClient.GetReportFindingAll(ctx, req)
	if err != nil {
		writeResponse(ctx, w, http.StatusInternalServerError, grpcErrorMessage(ctx, err))
		return
	}
	writeResponse(ctx, w, http.StatusOK, map[string]interface{}{successJSONKey: resp})
}
